### ISSUE TITLE
Misc Map Issues

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStation/HippieStation13-rebase#12]
It's probably best to redesign the map a tiny bit, not change it to mirror the original Hippie. So to create a new map from the base. But here are some must fix issues in my opinion.
The BAD
- Genetics has only one cloner. **(FIXED)**
- Medbay has two cryo only. **(FIXED)**
- Bizzare Detective's Office placement
- Mime and Clown office spawn with nothing in them and aren't even labelled, very strange. Also no privacy shutters. **(Somewhat fixed)**
-Security pod is way too small

The Neutral 

- Gravity generator is moved to the center of the station instead of engineering (makes more sense IMO but maybe some will disagree)
- No free public chem dispenser (seriously this idea was retarded) but I'm guessing that'll make a few people happy and angry **(FIXED)**
- Vacant Office is gone.. does anyone care?

THE GOOD
AI core is much better for now

**Comment by JamieH** [comment]
This is really useful - I'll merge this in with the Trello card we have for the map. FYI the Clown and Mime office weren't done, I just mapped the room out

**Comment by WallaceShark** [comment]
Assistants lose a lot of power without the chem dispenser. Gives more reason to break into medical for looting purposes, both as antag and greytide. I'd suggest either put a public chem dispenser in maint somewhere or figure out some way to make chemistry breakin harder.

**Comment by JamieH** [comment]
Yeah, I think we make a public chem dispenser.

**Comment by Pyko1** [comment]
We now have public chemdispenser, 3 cryos and 2 cloners.
Also clown/mime doors are labeled now.

**Comment by JamieH** [comment]
"Vacant Office is gone.. does anyone care?" - if this is an issue, we have a proposed solution, we'll wait to see if people have issues.

**Comment by cacogen** [comment]
isn't the ai core trivial to break into from space now?

**Comment by atomic1fire** [comment]
I posted this as a issue on one of the hippie station githubs but Detective's APC doesn't actually seem connected to detective's office on the rebase map (or one of the maps if you guys use more then one)

https://github.com/HippieStation/HippieStation13/issues/77

I have no idea where to submit rebase bugs so I closed it just in case.

I'm not too bothered by the placement considering Detective being close to HOP might not be a bad thing, but that APC makes Detective's office seem like it's being powered by a mystery power source.
