### ISSUE TITLE
Walls look strange and untextured.

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStation/HippieStation13-rebase#9]
I think that's just how walls look on /tg/. Very bland.

**Comment by Dudeinyourbackyard** [comment]
yep that's pretty much the problem, admiralhippie has always made our wall sprites so that they don't look so bland. you get used to it that the bland walls just look downright strange.

**Comment by JamieH** [comment]
I originally hated the Hippie walls but I've grown to like them - we'll put these in for sure.

**Comment by Carbonhell** [comment]
fixed in #19
